from enum import Enum

# goes to 61
class AudioDataFeature(Enum):
    # BASE FEATURES
    AUDIO_PATH = 0
    AUDIO_SAMPLES = 1
    AUDIO_SAMPLE_RATE = 2
    BPM = 12
    UUID = 46

    # INTERMEDIATE FEATURES
    HARMONIC_AUDIO = 13
    PERCUSSIVE_AUDIO = 14
    HARMONIC_MAGNITUDE_SPECTROGRAM = 15
    ONSET_ENVELOPE = 16
    ONSET_PEAKS = 17
    MULTI_BAND_ONSET_ENVELOPES = 18
    MULTI_BAND_ONSET_PEAKS = 19
    DYNAMIC_TEMPO = 20
    SPECTRAL_FLUX_ARRAY = 45
    SPECTRAL_CENTROID_ARRAY = 44
    LOUDNESS_ANALYSIS_RESULT = 51

    # LOUDNESS
    INTEGRATED_LUFS = 52
    CREST_FACTOR = 53
    LOUDNESS_RANGE_LU = 54
    TRUE_PEAK = 55
    RMS_IQR = 56
    RMS_MEAN = 57
    RMS_MAX = 58
    RMS_PERC = 59

    # FINAL SPECTRAL FEATURES
    SPECTRAL_CENTROID_MEAN = 21
    SPECTRAL_CENTROID_MAX = 22
    SPECTRAL_CENTROID_STD = 61
    SPECTRAL_FLUX_MEAN = 23
    SPECTRAL_FLUX_MAX = 24
    SPECTRAL_FLUX_STD = 62
    SPECTRAL_ROLLOFF_MEAN = 25
    SPECTRAL_ROLLOFF_STD = 26
    SPECTRAL_FLATNESS_MEAN = 27
    SPECTRAL_CONTRAST_MEAN = 28
    HARMONICITY = 29
    ZCR_MEAN = 30

    # FINAL RHYTHMIC FEATURES
    ONSET_ENV_MEAN_GLOBAL = 31
    ONSET_RATE_GLOBAL = 32
    TEMPO_VARIATION = 33
    ONSET_ENV_MEAN_KICK = 34
    ONSET_RATE_KICK = 35
    ONSET_ENV_MEAN_SNARE = 36
    ONSET_RATE_SNARE = 37
    ONSET_ENV_MEAN_LOW_MID = 38
    ONSET_RATE_LOW_MID = 39
    ONSET_ENV_MEAN_HI_HAT = 40
    ONSET_RATE_HI_HAT = 41

    # MFCC FEATURES
    MFCC_MEANS = 42
    MFCC_STDS = 43

    # KEYS
    PRINCIPAL_KEY = 47
    START_KEY = 48
    END_KEY = 49
    KEY_PROGRESSION = 50

    # MISC
    ENERGY_LEVEL = 60
